version: "2"
services:
  api:
    image: glr.honestbee.com/honestbee/vrp_sample:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "80:5000"
    volumes:
      - apidata:/var/data
  
  redis:
    image: redis:3.2.5

volumes:
  apidata:
